### ISSUE TITLE
In WatchDog reports, test executions are no longer shown

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#204]
In the statistics in the Eclipse IDE, these executions are reported. I executed tests 4 times.

http://testroots.org/reports/project/75830647b4bc18c7c6f5a0cc5df2b7b3eaac2413.html

**Comment by levaja** [comment]
All of these 4 intervals are registered correctly on the server.

**Comment by levaja** [comment]
Apparently, this only happens for Eclipse projects. I've sampled a few Eclipse and IntelliJ projects which have test execution intervals on server and only Eclipse reports are missing this. IntelliJ reports look ok.

**Comment by Inventitech** [comment]
Thanks for investigating this, @levaja. I'll take it from here.

**Comment by levaja** [comment]
I've found the error, it's my fault. I will report here as soon as I come up with a solution for plugin, as well as for database cleanup (although you will probably have to execute the command on server).

**Comment by levaja** [comment]
In short, the error is in the fields' names (full names instead of abbreviations). We got "parent" instead of "p", "childrenExecutions" instead of "c" etc.

```
"testExecution" : { "projectHash" : "23812046aa94d58224f0ea1309f557dbaf1eee6a", "result" : "F", "duration" : 1.496000051498413, "childrenExecutions" : [ { "testClassHash" : "914ece8cee76a984575a0c0f1176c27272b19be8Test", "result" : "F", "duration" : 1.496000051498413, "childrenExecutions" : [ { "testMethodHash" : "37d714acabf8794974145e3990ae377480b55b32", "result" : "F", "duration" : 1.496000051498413 } ] } ] }
```
This first happened with IntelliJ intervals, I thought I fixed this. The issue occurs after dividing plugins into Core and Plugins - name serialization does not propagate correctly through 2 projects (Plugin+Core). I will check what went wrong and try to apply the same solution as in IntelliJ.

Considering the database, $rename command will certainly do the job. I will follow up on this later.

**Comment by levaja** [comment]
So the bug is fixed in code. In database, it's necessary to fix field names, at the moment there are between 4 and 5 thousands affected intervals, which can be checked with this command:

`db.intervals.count({"testExecution":{$exists:true}})`

For fixing, I still need to ensure that the following commands will certainly update and fix interval format, so **don't execute them yet** (actually, it will be necessary to run them a few more times later on, because of the users who will still use 1.5.0 version of WD).

`db.intervals.update({}, {$rename:{"testExecution":"je"}}, false, true)`
`db.intervals.update({}, {$rename:{"je.duration":"je.d"}}, false, true)`
`db.intervals.update({}, {$rename:{"je.projectHash":"je.p"}}, false, true)`
`db.intervals.update({}, {$rename:{"je.result":"je.r"}}, false, true)`
`db.intervals.update({}, {$rename:{"je.childrenExecutions":"je.c"}}, false, true)`

However, for tests in array, it will be a bit difficult to change field names, but I'll do my best to come up with a solution.

**Comment by levaja** [comment]
Luckily, it is possible to change fields in an array as well, although there's no native support in MongoDB in it, so it has to be done manually:

``` 
db.intervals.find({"je.c.0.testClassHash":{ $exists: true } }).forEach(function(item) { 
  for(i = 0; i != item.je.c.length; ++i) { 
    item.je.c[i].t = item.je.c[i].testClasssHash;  
    delete item.je.c[i].testClassHash; 
  }  
  db.intervals.update({_id: item._id}, item);});

db.intervals.find({"je.c.0.result":{ $exists: true } }).forEach(function(item) { 
  for(i = 0; i != item.je.c.length; ++i) { 
    item.je.c[i].r = item.je.c[i].result;  
    delete item.je.c[i].result; 
  }  
  db.intervals.update({_id: item._id}, item);});

db.intervals.find({"je.c.0.duration":{ $exists: true } }).forEach(function(item) { 
  for(i = 0; i != item.je.c.length; ++i) { 
    item.je.c[i].d = item.je.c[i].duration;  
    delete item.je.c[i].duration; 
  }  
  db.intervals.update({_id: item._id}, item);});

db.intervals.find({"je.c.0.childrenExecutions":{ $exists: true } }).forEach(function(item) { 
 for(i = 0; i != item.je.c.length; ++i) { 
    item.je.c[i].c = item.je.c[i].childrenExecutions;  
    delete item.je.c[i].childrenExecutions; 
  }  
db.intervals.update({_id: item._id}, item);});


db.intervals.find({"je.c.0.c.0.testMethodHash":{ $exists: true } }).forEach(function(item) { 
	for(i = 0; i != item.je.c.length; ++i) { 
		for(j = 0; j!= item.je.c[i].c.length; ++j) {
		  item.je.c[i].c[j].m = item.je.c[i].testMethodHash;  
		  delete item.je.c[i].c[j].testMethodHash; } }		
	db.intervals.update({_id: item._id}, item);});

db.intervals.find({"je.c.0.c.0.result":{ $exists: true } }).forEach(function(item) { 
	for(i = 0; i != item.je.c.length; ++i) { 
		for(j = 0; j!= item.je.c[i].c.length; ++j) {
		  item.je.c[i].c[j].r = item.je.c[i].result;  
		  delete item.je.c[i].c[j].result; } }		
	db.intervals.update({_id: item._id}, item);});
	
db.intervals.find({"je.c.0.c.0.duration":{ $exists: true } }).forEach(function(item) { 
	for(i = 0; i != item.je.c.length; ++i) { 
		for(j = 0; j!= item.je.c[i].c.length; ++j) {
		  item.je.c[i].c[j].d = item.je.c[i].duration;  
		  delete item.je.c[i].c[j].duration; } }		
	db.intervals.update({_id: item._id}, item);});
```

I am aware that this looks ugly, but at the moment I believe this is the best solution. Still need to test it a bit more, but so far it works fine.

**Comment by levaja** [comment]
Okay, ignore the previous code because it only fixes about 90% of the intervals. The following code, I'm quite sure, will fix all of them:

**Function that iterates through the single interval recursively:**
```
db.system.js.save({_id:"Recursion", value: function recursion (c) {
if(c != null) {	
		if(c.duration != null) {
			c.d = c.duration;
			delete c.duration;}
		if(c.projectHash != null) {
			c.p = c.projectHash;
			delete c.projectHash;}
		if(c.result != null) {
			c.r = c.result;
			delete c.result;}	
		if(c.testClassHash != null) {
			c.t = c.testClassHash;
			delete c.testClassHash;}
		if(c.testMethodHash != null) {
			c.m = c.testMethodHash;
			delete c.testMethodHash;}
		if(c.childrenExecutions != null) {
			c.c = c.childrenExecutions;
			delete c.childrenExecutions;
			for(var i = 0; i < c.c.length; i++) {
			var a = recursion(c.c[i]);}}}}
			});
```

**Function that fixes a single interval:**
```
db.system.js.save({_id:"FixIntervals", value: function(item) {
	if(item.testExecution != null) {
		item.je = item.testExecution;
		delete item.testExecution;}	
	b = Recursion(item.je);
	db.intervals.update({_id: item._id}, item);            
}});
```
**Command to execute:**
`db.intervals.find({"testExecution":{$exists:true}}).forEach(FixIntervals);`

The first 2 functions will be saved on server, so later on it will be enough just to load them with: `db.loadServerScripts();`

I've manually  checked the intervals and I believe that this will fix this issue. Once again, I'm sorry for causing this one.

**Comment by Inventitech** [comment]
Igor, can I delete https://github.com/TestRoots/watchdog/issues/204#issuecomment-154209073 and https://github.com/TestRoots/watchdog/issues/204#issuecomment-154146269 so that we do not get confused when doing this?

**Comment by levaja** [comment]
Deleted :)

**Comment by Inventitech** [comment]
`> db.intervals.count({"testExecution":{$exists:true}});
9175`

and after executing it:

`> db.intervals.count({"testExecution":{$exists:true}});
0
> db.intervals.count({"je":{$exists:true}});
70944`

That seems to have worked; excellent. Thanks!

I just hope nobody is using this ancient WD-version anymore ...

**Comment by Inventitech** [comment]
This needs to be done on an on-going basis.
