### ISSUE TITLE
When clicking on Cancel in Project Registration, Anonymous registration option is not offered

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#207]
This was observed with WD 1.5

**Comment by levaja** [comment]
Actually, this is more like intended behaviour, but I see your point.

Since a user already gets a question "Should WatchDog be active in this workspace?", and wizard is displayed only if he clicks "Yes", I think that if he Cancel this wizard we should perform anonymous registration anyway. 
We shouldn't bother him again with a question, he already said that he wants to monitor that Project, but doesn't want to complete the wizard.

Is this good solution?
