### ISSUE TITLE
WatchDog cannot be imported in Eclipse

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#208]
Importing WatchDog project into a recent Eclipse yields compile errors in WatchDog, WatchDogUnitTests and WatchDogFeature (which can be mitigated through disabling its Maven nature).

Moreover, there are two WatchDogFeature in both EclipsePlugin/ and Core. Why? They cannot both be present in the workspace at the same time.

**Comment by levaja** [comment]
Okay, I've just tested this:

1) Downloaded latest Eclipse installation. Created a new workspace.
2) Imported WatchDog Eclipse plugin first (some expected compilation error, due to missing Core). ("Import existing project into workspace").
3) Imported WatchDog Core -> No more compilation errors.

I guess the only problem was with WatchDogFeature in Core. Since I used that only in command line build, I didn't import it to Eclipse initially. Now it's renamed so no more problems with it.

**Comment by Inventitech** [comment]
:+1:
