### ISSUE TITLE
WatchDog does not load in Eclipse/Windows

### ISSUE THREAD

**Issue by Inventitech** [TestRoots/watchdog#306]
WatchDog is not loaded in Eclipse Windows.

![wd_not_loaded](https://user-images.githubusercontent.com/334256/39544590-d52673a0-4e4e-11e8-97d0-693c8b442ce9.png)

After importing the project, this is the error I receive. Importing the package (which is the proper/preferred way) does not fix the problem (https://blog.osgi.org/2008/06/jsr-277-and-import-package.html), nor does lowering the severity to a warning.

![change_warning_level_for_forbidden_reference](https://user-images.githubusercontent.com/334256/39544657-0b4a97e0-4e4f-11e8-95a5-78e24660349a.png)

```
org.osgi.framework.BundleException: Could not resolve module: nl.tudelft.WatchDog [175]
  Unresolved requirement: Import-Package: org.eclipse.ui.browser
```

**Comment by TimvdLippe** [comment]
Copying my message from Mattermost:

I have generated the WatchDog bundle and installed it in an Eclipse installation on Windows 10 and have verified it works. You can reproduce this by following these steps:

1. Take the zip attached to this message
1. Help -> Install new Software
1. On the right click Add...
1. Click Archive
1. Select the download zip
1. Install the artifacts per the usual Eclipse installation instructions

For the archive, please see our channel in Mattermost.

**Comment by Inventitech** [comment]
Adding the bundle via the add require tooltip solves this problem, but introduces the unwanted bundle dependency. It is very strange that the import package solution does not work. I wonder whether the optional flag in `org.eclipse.ui.browser;resolution:=optional` has something to do with it.

**Comment by Inventitech** [comment]
(Also: why is it optional?)

**Comment by TimvdLippe** [comment]
It is optional because not every Eclipse installation ships with that package. This is mostly a security issue, as exposing the browser via Eclipse is considered a risk. The error is therefore a warning (also disabled in a Maven build), but I am not sure why Eclipse on Windows complains about this, while Eclipse Ubuntu works just fine.

I would say, let's investigate WatchDog development on Windows after the release. I can then have a fresh look and also look into making the install scripts cross-platform. (As the plugin is confirmed working on Windows per https://github.com/TestRoots/watchdog/issues/306#issuecomment-386254806)
